/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ta;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
/**
 *
 * @author Muhammad Heriyanto
 */
public class PopUpSupplier extends javax.swing.JFrame {
private Koneksi tb;
public static Connection con;
public static ResultSet res;
public static Statement stm;
private StockSupplier stockSupplier;
private String[] rowData;
    /**
     * Creates new form PopUpSupplier
     */
    public PopUpSupplier(StockSupplier stockSupplier, String[] rowData) {
        initComponents();
        this.stockSupplier = stockSupplier;
        this.rowData = rowData;
         if (rowData != null) {
         String KodeSupplier= rowData[0];
         String NamaSupplier= rowData[1];
         String DetailBahan= rowData[2];
         String Alamat= rowData[3];
         String Telp= rowData[4];
         
         kdsp.setText(KodeSupplier);
         nssp.setText(NamaSupplier);
         dbsp.setText(DetailBahan);
         almsp.setText(Alamat);
         tpsp.setText(Telp);
                
    } else {
        kdsp.setText("");
         nssp.setText("");
         dbsp.setText("");
         almsp.setText("");
         tpsp.setText("");
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kdsp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nssp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dbsp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        almsp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tpsp = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(210, 180, 140));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Kode Supplier");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nama Supplier");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Detail Bahan");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Alamat");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Telp");

        jButton1.setBackground(new java.awt.Color(204, 133, 63));
        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(kdsp)
                        .addComponent(nssp)
                        .addComponent(dbsp)
                        .addComponent(almsp)
                        .addComponent(tpsp, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                    .addComponent(jButton1))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kdsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nssp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dbsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(almsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tpsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      tb = new Koneksi();
      tb.koneksimysql();
     java.sql.Connection con = tb.con;
java.sql.PreparedStatement stm=null;
          try {
    
    String sql = "SELECT * FROM supplier WHERE KodeSupplier = ?";
stm = con.prepareStatement(sql);
stm.setString(1, kdsp.getText());
ResultSet res = stm.executeQuery();


if (res != null && res.next()) {
    String count = res.getString(1);

    // Data sudah ada di database, lakukan operasi update
    String updateSql = "UPDATE supplier SET KodeSupplier = ?, NamaSupplier = ?, DetailBahan = ?, Alamat = ?, Telp = ? WHERE KodeSupplier = ?";
    stm = con.prepareStatement(updateSql);
    stm.setString(1, kdsp.getText());
    stm.setString(2, nssp.getText());
    stm.setString(3, dbsp.getText());
    stm.setString(4, almsp.getText());
    stm.setString(5, tpsp.getText());
    stm.setString(6, kdsp.getText());

    int rowsUpdated = stm.executeUpdate();
    if (rowsUpdated > 0) {
        System.out.println("Data diupdate.");
    } else {
        System.out.println("Gagal melakukan update data.");
    }

    stm.close();
} else {
    // Data belum ada di database, lakukan operasi insert
    String insertSql = "INSERT INTO supplier ( KodeSupplier, NamaSupplier, DetailBahan, Alamat, Telp) VALUES (?, ?, ?, ?, ?)";
    stm = con.prepareStatement(insertSql);
    stm.setString(1, kdsp.getText());
    stm.setString(2, nssp.getText());
    stm.setString(3, dbsp.getText());
    stm.setString(4, almsp.getText());
    stm.setString(5, tpsp.getText());
    
   

    int rowsInserted = stm.executeUpdate();
    if (rowsInserted > 0) {
        System.out.println("Data diinsert.");
    } else {
        System.out.println("Gagal melakukan insert data.");
    }

    stm.close();
} 
    System.out.println(kdsp.getText());
    System.out.println(nssp.getText());
    System.out.println(dbsp.getText());
    System.out.println(almsp.getText());
    System.out.println(tpsp.getText());



stockSupplier.tabelsupplier();

    setVisible(false);
    
    
    
    
} catch (Exception e) {
    e.printStackTrace(); // Ubah ini menjadi tindakan yang lebih spesifik jika diperlukan
}
    }//GEN-LAST:event_jButton1ActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {5
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PopUpSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PopUpSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PopUpSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PopUpSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PopUpSupplier().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField almsp;
    private javax.swing.JTextField dbsp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kdsp;
    private javax.swing.JTextField nssp;
    private javax.swing.JTextField tpsp;
    // End of variables declaration//GEN-END:variables
}
